trigger:
        - main

        pool:
          vmImage: 'ubuntu-2004' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'boris19944/herveprestashop:1.0'

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile